[project]
name = "mkdocs-vegalite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs>=1.6",
    "pymdown-extensions>=9.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mkdocs_vegalite"]

[project.entry-points.'mkdocs.plugins']
mkdocs_vegalite = "mkdocs_vegalite:MkDocsVegalitePlugin"
