# build-environment.yml
name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server==2.17.0
  - jupyterlite-core >=0.6
  - jupyterlite-xeus >=0.4
  - jupyterlite-javascript-kernel=0.3.0
  - jupyterlite-pyodide-kernel=0.6.1
  - pip:
      - catppuccin-jupyterlab==0.2.4
