name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server=2.16.0
  - jupyterlite-core=0.6.2
  - jupyterlite-xeus=4.0.3
  - jupyterlite-javascript-kernel=0.3.0
  - jupyterlite-pyodide-kernel=0.6.1
  - jupyterlite-terminal=0.2.1
