name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python=3.11
  - xeus-python=0.17.2
  - xeus-javascript=0.4.0
  - scikit-learn
  - scipy
  - pandas
  - numpy
  - matplotlib
  - plotly
  - jupyterlab-filesystem-access
  - jupyterlab-open-url-parameter
