name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.6
  - jupyterlite-xeus >=0.4
  - jupyterlite-javascript-kernel=0.3.0
  - jupyterlite-pyodide-kernel=0.6.1
