name: xeus-kernels
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python=3.11
  - xeus-python
  - xeus-sqlite
  - xeus-javascript
  - xeus-r
  - r-coursekata
  - scikit-learn=1.1.3
  - scipy=1.11.1
  - pandas=2.2.3
  - numpy=1.25.2
  - matplotlib=3.9.4
  - seaborn=0.13.2
  - plotly=6.1.2
  - ipywidgets=8.1.7
  - rich=14.0.0
  # - jupyterlab-open-url-parameter
  # - jupyterlab-filesystem-access
  - pip
  - pip:
      - jupyterlite-ai==0.7.0
      # - jupyterlab-night
      # - jupyterlab_miami_nights
      # - catppuccin-jupyterlab
